alias i='iex'
alias ism='iex -S mix'
alias ips='iex -S mix phoenix.server'
alias m='mix'
alias mc='mix compile'
alias mn='mix new'
alias mns='mix new --sup'
alias mr='mix run'
alias mrnh='mix run --no-halt'
alias mt='mix test'
alias mdc='mix deps.compile'
alias mdg='mix deps.get'
alias mdu='mix deps.update'
alias mdua='mix deps.update --all'
alias meb='mix escript.build'
alias mec='mix ecto.create'
alias mem='mix ecto.migrate'
alias mpn='mix phoenix.new'
alias mps='mix phoenix.server'
alias mpr='mix phoenix.routes'
alias mpgm='mix phoenix.gen.model'
alias mpgh='mix phoenix.gen.html'
alias mpgj='mix phoenix.gen.json'
alias mpgc='mix phoenix.gen.channel'

# Heroku
alias hrmec='heroku run mix ecto.create'
alias hrmem='heroku run mix ecto.migrate'
